# Generated by Django 5.0.3 on 2024-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_servicerequest_submission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='submission_date',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
