# Generated by Django 5.0.3 on 2024-03-20 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_servicerequest_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='resolution_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='submission_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
