# Generated by Django 5.0.3 on 2024-03-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_servicerequest_resolution_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='resolution_datetime',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='submission_datetime',
        ),
    ]
